upd: Windows install command added.
gnojus/wedl pull request #8
Opened 2024-04-14 16:07 UTC by ramazansancar

https://github.com/gnojus/wedl/pull/7

2024-04-15 09:47 UTC, gnojus requested changes
Thanks, see my comments

2024-04-15 09:47 UTC, gnojus commented on README.md
> +go mod download
no need to run `go mod download`. go build will to this automatically.

2024-04-15 09:47 UTC, gnojus commented on README.md
> +# Build
AFAIK cmd uses `::` as comments, so this shoud be `:: Build`.  ditto for others in this windows block

2024-04-15 15:00 UTC, ramazansancar commented on README.md
> +go run . https://go.wetransfer.com/responsibility #Download to stdout
I don't quite understand what you mean here. Can you give a little more detail? @gnojus

2024-05-05 20:42 UTC, ramazansancar commented
Check pls @gnojus

2024-05-27 10:45 UTC, merged

2024-05-27 10:53 UTC, gnojus commented
Hi, sorry for the long delay. I merged in your changes and did some cleanup afterwards. Thanks.

2024-05-27 17:12 UTC, ramazansancar commented
Thanks for editing and Merge